services:

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    networks:
      - database
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.adminer.entrypoints=http"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.rule=Host(`adminer.local.antoniocaccamo-labs.it`)"
      # - "traefik.http.middlewares.adminer-https-redirect.redirectscheme.scheme=https"
      # - "traefik.http.routers.adminer.middlewares=adminer-https-redirect"
      # - "traefik.http.routers.adminer-secure.entrypoints=https"
      # - "traefik.http.routers.adminer-secure.rule=Host(`adminer.local.antoniocaccamo-labs.it`)"
      # - "traefik.http.routers.adminer-secure.tls=true"
      # - "traefik.http.routers.adminer-secure.service=adminer"


networks:
  proxy:
    external: true
  database:
    external: true