apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: traefik
spec:
  type: ExternalName
  externalName: login.private.antoniocaccamo.work 

---

apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: default
spec:
  type: ExternalName
  externalName: login.private.antoniocaccamo.work 