apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-lab-az-ai-deploy
  namespace: lab-az-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-az-ai
      component: webapp
  template:
    metadata:
      labels:
        app: lab-az-ai
        component: webapp
    spec:
      imagePullSecrets:
        - name: pcr-secret
      containers:
        - name: webapp-lab-az-ai
          image: registry.private.antoniocaccamo.work/lab-az-ai/webapp-lab-az-ai:1.0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          env:
          - name: TENANT_ID
            value: "53695c6a-e1de-42b9-be99-97f60ccfd8b0"
          - name: WEBAPP_CLIENT_ID
            value: "1c2110d7-3081-4451-a3cc-f5dc14c9d74d"
          - name: WEBAPP_CLIENT_SECRET
            value: "Jei8Q....."
